name: charming_nico
services:
  main_app:
    cpu_shares: 90
    command: []
    container_name: torrserve
    deploy:
      resources:
        limits:
          memory: 64M
    environment:
      TZ: $TZ 
    image: ksey/torrserver:latest
    labels:
      icon: https://freesoft.ru/storage/images/746/7460/745969/745969_normal.png
    ports:
      - target: 8090
        published: "22006"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DockerHub/TorrServe-MatriX_2/TS/db
        target: /TS/db
    devices: []
    cap_add: []
    network_mode: bridge
    privileged: false
    hostname: torrserve
x-casaos:
  author: self
  category: self
  hostname: ""
  icon: https://freesoft.ru/storage/images/746/7460/745969/745969_normal.png
  index: /
  is_uncontrolled: false
  port_map: "22006"
  scheme: http
  store_app_id: charming_nico
  title:
    custom: TorrServe MatriX
